/**
 * STL (binary) exporter for Three.js BufferGeometry / raw mesh data
 * Binary STL is the preferred format for OnShape import.
 */

import type { MeshData } from '../meshing/poisson'

/**
 * Export mesh data to binary STL ArrayBuffer
 */
export function exportSTL(mesh: MeshData, scale: number = 1000): ArrayBuffer {
  // scale: 1000 converts meters to millimeters (standard for OnShape)
  const { vertices, indices, normals } = mesh
  const numTriangles = indices.length / 3

  // Binary STL format:
  // 80 bytes header
  // 4 bytes: number of triangles
  // Per triangle: 12 bytes normal + 3×12 bytes vertices + 2 bytes attribute
  const bufferSize = 80 + 4 + numTriangles * (12 + 36 + 2)
  const buffer = new ArrayBuffer(bufferSize)
  const view = new DataView(buffer)

  // Write header (80 bytes ASCII)
  const header = 'LiDAR 3D Scanner - Generated by lidar-scanner.app'
  for (let i = 0; i < Math.min(header.length, 80); i++) {
    view.setUint8(i, header.charCodeAt(i))
  }

  // Number of triangles
  view.setUint32(80, numTriangles, true)

  let offset = 84

  for (let i = 0; i < numTriangles; i++) {
    const i0 = indices[i * 3]
    const i1 = indices[i * 3 + 1]
    const i2 = indices[i * 3 + 2]

    // Compute face normal (average of vertex normals)
    const nx = (normals[i0 * 3] + normals[i1 * 3] + normals[i2 * 3]) / 3
    const ny = (normals[i0 * 3 + 1] + normals[i1 * 3 + 1] + normals[i2 * 3 + 1]) / 3
    const nz = (normals[i0 * 3 + 2] + normals[i1 * 3 + 2] + normals[i2 * 3 + 2]) / 3
    const nl = Math.sqrt(nx * nx + ny * ny + nz * nz) || 1

    // Normal vector
    view.setFloat32(offset, nx / nl, true); offset += 4
    view.setFloat32(offset, ny / nl, true); offset += 4
    view.setFloat32(offset, nz / nl, true); offset += 4

    // Vertices (3 per triangle, scaled to mm)
    for (const idx of [i0, i1, i2]) {
      view.setFloat32(offset, vertices[idx * 3] * scale, true); offset += 4
      view.setFloat32(offset, vertices[idx * 3 + 1] * scale, true); offset += 4
      view.setFloat32(offset, vertices[idx * 3 + 2] * scale, true); offset += 4
    }

    // Attribute byte count (always 0)
    view.setUint16(offset, 0, true); offset += 2
  }

  return buffer
}

/**
 * Export point cloud as binary PLY
 */
export function exportPLY(points: Float32Array, scale: number = 1000): ArrayBuffer {
  const numPoints = points.length / 3

  const header = [
    'ply',
    'format binary_little_endian 1.0',
    'comment Generated by LiDAR 3D Scanner',
    `element vertex ${numPoints}`,
    'property float x',
    'property float y',
    'property float z',
    'end_header',
    '',
  ].join('\n')

  const headerBytes = new TextEncoder().encode(header)
  const dataBytes = new ArrayBuffer(numPoints * 12) // 3 floats × 4 bytes
  const view = new DataView(dataBytes)

  for (let i = 0; i < numPoints; i++) {
    view.setFloat32(i * 12, points[i * 3] * scale, true)
    view.setFloat32(i * 12 + 4, points[i * 3 + 1] * scale, true)
    view.setFloat32(i * 12 + 8, points[i * 3 + 2] * scale, true)
  }

  // Concatenate header and data
  const result = new Uint8Array(headerBytes.length + dataBytes.byteLength)
  result.set(headerBytes, 0)
  result.set(new Uint8Array(dataBytes), headerBytes.length)
  return result.buffer
}

/**
 * Export mesh as OBJ text
 */
export function exportOBJ(mesh: MeshData, scale: number = 1000): string {
  const { vertices, indices, normals } = mesh
  const lines: string[] = [
    '# LiDAR 3D Scanner - OBJ Export',
    `# Vertices: ${vertices.length / 3}`,
    `# Triangles: ${indices.length / 3}`,
    '',
    'mtllib model.mtl',
    'o ScannedObject',
    '',
  ]

  // Vertices
  for (let i = 0; i < vertices.length / 3; i++) {
    const x = (vertices[i * 3] * scale).toFixed(4)
    const y = (vertices[i * 3 + 1] * scale).toFixed(4)
    const z = (vertices[i * 3 + 2] * scale).toFixed(4)
    lines.push(`v ${x} ${y} ${z}`)
  }

  lines.push('')

  // Normals
  for (let i = 0; i < normals.length / 3; i++) {
    const nx = normals[i * 3].toFixed(6)
    const ny = normals[i * 3 + 1].toFixed(6)
    const nz = normals[i * 3 + 2].toFixed(6)
    lines.push(`vn ${nx} ${ny} ${nz}`)
  }

  lines.push('')
  lines.push('usemtl Material')
  lines.push('s off')
  lines.push('')

  // Faces (1-indexed in OBJ)
  for (let i = 0; i < indices.length / 3; i++) {
    const a = indices[i * 3] + 1
    const b = indices[i * 3 + 1] + 1
    const c = indices[i * 3 + 2] + 1
    lines.push(`f ${a}//${a} ${b}//${b} ${c}//${c}`)
  }

  return lines.join('\n')
}

export function exportMTL(): string {
  return [
    '# LiDAR 3D Scanner - MTL Export',
    'newmtl Material',
    'Ns 96.078431',
    'Ka 0.000000 0.000000 0.000000',
    'Kd 0.640000 0.640000 0.640000',
    'Ks 0.500000 0.500000 0.500000',
    'Ke 0.000000 0.000000 0.000000',
    'Ni 1.000000',
    'd 1.000000',
    'illum 2',
  ].join('\n')
}

/**
 * Trigger a file download in the browser
 */
export function downloadFile(data: ArrayBuffer | string, filename: string, mimeType: string): void {
  const blob = typeof data === 'string'
    ? new Blob([data], { type: mimeType })
    : new Blob([data], { type: mimeType })

  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
